const universities = [
  'Case Western Reserve University',
  'Columbia University',
  'Georgia Institute of Technology',
  'George Washington University',
  'Harvard Extension School',
  'John Hopkins University',
  'Monash University',
  'Northwestern University',
  'Rice University',
  'Rutgers University',
  'Southern Methodist University',
  'Tecnológico de Monterrey, Mexico',
  'University of Adelaide',
  'University of Arizona',
  'University of Birmingham',
  'University of California - Berkeley',
  'University of California - Davis',
  'University of California - Irvine',
  'University of California - Los Angeles',
  'University of California - Riverside',
  'University of California - San Diego',
  'University of California - San Francisco',
  'University of Central Florida',
  'University of Connecticut',
  'University of Denver',
  'University of Kansas',
  'University of Manchester',
  'University of Massachusetts - Amherst',
  'University of Miami',
  'University of Minnesota',
  'University of New Hampshire',
  'University of North Carolina - Chapel Hill',
  'University of North Carolina - Charlotte',
  'University of North Carolona - Raleigh',
  'University of Oregon',
  'University of Pennsylvania',
  'University of Richmond',
  'University of Southern California',
  'University of Texas - Austin',
  'University of Texas - Houston',
  'University of Texas - San Antonio',
  'University of Toronto',
  'University of Utah',
  'University of Washington - Seattle',
  'University of Western Australia',
  'University of Wisconsin - Madison',
  'Vanderbilt University',
  'Washington University - St. Louis'
];

export default universities;